### ISSUE TITLE
Problem implementing unitary tests

### ISSUE THREAD

**Issue by uo270411** [Arquisoft/radarin_en3a#108]
Good afternoon @pglez82.
We are having a problem with some components related to unitary tests.
The error is on the test branch, and we are getting it with both mapView test and marker test. As you can see, test passes but the test suite is failing. The error is the following:
![ErrorMapView](https://user-images.githubusercontent.com/71767155/116567249-bf0b8300-a907-11eb-96c5-0bcc381316bf.PNG)
![ErrorTests](https://user-images.githubusercontent.com/71767155/116567257-c03cb000-a907-11eb-8b97-3413bdd3079f.PNG)

**Comment by pglez82** [comment]
In which branch this tests are failing?

**Comment by uo270411** [comment]
These tests are implemented in test branch.

**Comment by pglez82** [comment]
It checked the test in Marker.test.js. The thing is that usually, in unitary tests, is not as easy as rendering the component. You need to understand the component and check the implementation to see what the component need to be rendered. If you check the implementation of the MarkerGenerator component, it is calling the pod, and reading some properties so it renders properly. What you need to do is to mock up this parts so it doesn't need the pod information to render. More information here:

https://jestjs.io/docs/mock-functions

**Comment by uo270411** [comment]
Ok, i Will check It, thank you!!
