### ISSUE TITLE
React research

### ISSUE THREAD

**Issue by raulng9** [Arquisoft/radarin_en3a#20]
Possible libraries to use:
[React Native for the mobile application](https://reactnative.dev/)
[React Native Get Location library](https://www.npmjs.com/package/react-native-get-location) 
[Geolib for distance calculations](https://www.npmjs.com/package/geolib)
[React components for SOLID](https://github.com/solid/react-components)
[Solid and React apps](https://github.com/solid/information/blob/master/documentation/apps.md#writing-solid-applications-with-react)

**Comment by uo269570** [comment]
To build an movile app we can see this video to help us create a base up and run it.
https://www.youtube.com/watch?v=6ZnfsJ6mM5c

**Comment by uo269570** [comment]
The last link I shared whas not a good tutorial. I coudn´t see the demo app working properly. This other video help me have the app running in a emulator. The guy in the video uses another app to have the emulators but with android studio ones it also works perfectly. 
https://www.youtube.com/watch?v=WnS7dcY5Hys
We can also see the app deployed in our android devices, I recomend to see this if you are goinf to work with the movile app part of the project.
