### ISSUE TITLE
PODs accounts

### ISSUE THREAD

**Issue by UO269509** [Arquisoft/radarin_en3a#28]
I create my account: https://francisco-en3a.solidcommunity.net/profile/card#me

**Comment by uo269570** [comment]
My account it this: https://uo269570.solidcommunity.net/profile/card#me

**Comment by raulng9** [comment]
My profile is: https://raulng.inrupt.net/profile/card#me  it's with Inrupt as the provider.

**Comment by uo270411** [comment]
My profile is: https://sergioen3a.inrupt.net/profile/card#me

**Comment by UO225811** [comment]
My profile is this: https://sferlo.inrupt.net/profile/card#me

**Comment by ArCampa** [comment]
My profile is https://arcampa.solidcommunity.net/profile/card#me

**Comment by UO269509** [comment]
I'm going to close the issue because we are already friends in Solid.
