### ISSUE TITLE
Solid components in mobile app

### ISSUE THREAD

**Issue by uo269570** [Arquisoft/radarin_en3a#35]
Research on how to use the solid component in mobile app, if it is possible or not ...

**Comment by uo269570** [comment]
Errors trying to use the library of solid-node-client. I added below the inports this code
import { SolidNodeClient } from 'solid-node-client';
const client = new SolidNodeClient();
I also installed the package in the project. But trying to run this with the emulator gives me an error like this one:
![imagen](https://user-images.githubusercontent.com/60401888/111042050-a1f42100-843b-11eb-91f4-ef4990749874.png)
Any clue how to solve this?

**Comment by pglez82** [comment]
@UO269509, we are having a similar conversation with another group in this [issue](https://github.com/Arquisoft/radarin_en2b/issues/44#issuecomment-797730766). You can follow it there so we do not duplicate information.

**Comment by uo269570** [comment]
https://forum.solidproject.org/t/login-in-solid-pods-with-react-native/4116 I have just created an enter in the forum about this matter @pglez82

**Comment by pglez82** [comment]
@uo269570, have you been able to get it working?

**Comment by uo269570** [comment]
@pglez82 no, I had the same problem as the guy in the forum, I am trying different things but I am afraid I will not be able to do the login

**Comment by uo269570** [comment]
@pglez82 Regarding this, we are going to have to some part of the mobile app working with the notifications and that things? Because I think all relates on wheter or not we are able to log in in the pod in order to recieve notifications and to save the location of the user.

**Comment by pglez82** [comment]
@uo269570 You need to have a back up plan in case you are not able to log in from react native. Other groups are struggling with the same problem and up to now, there seems to be no easy solution to the problem. Maybe one option is to implement the functionality of the mobile app in the webapp directly. Another possible option is to change the architecture and do the solid operations through the node restapi (mobile app->restapi->solid server). 

Remember that the idea for next week (lab session 10) is having the basic functionality of the assignment working so you are in a critical point now. It is also important to note that in the case of changing the architecture, the documentation should reflect these changes and the reason for them. We as teachers are aware of this react native/solid problem and will take that into consideration.

**Comment by uo269570** [comment]
As the mobile app is not longer being implemented I am closing this issue
