### ISSUE TITLE
Map provider research

### ISSUE THREAD

**Issue by raulng9** [Arquisoft/radarin_en3a#39]
Options:

- [Google Maps](https://developers.google.com/maps?hl=es): mainly paying options except for mobile.
- [HERE Maps](https://developer.here.com/documentation/map-tile/dev_guide/topics/introduction.html): up to 250k transactions per month for free.
- [Mapbox](https://www.mapbox.com/pricing/#vectortile): up to 200k tile requests per month for free.
- [OpenLayers](https://openlayers.org/en/latest/apidoc/): free without restrictions.
- [Leaflet](https://leafletjs.com/reference-1.7.1.html): free without restrictions.
- [React Leaflet](https://react-leaflet.js.org/): Leaflet.js components for use with React.
- [Comparison between OpenLayers and Leaflet.js](https://www.geoapify.com/leaflet-vs-openlayers)

**Comment by UO269509** [comment]
I think, we can implement it using Leaflet, what do you think?

**Comment by raulng9** [comment]
Yes, I think it might be the best option due to the lack of limitations of the API and the amount of documentation available online about it.

**Comment by raulng9** [comment]
We finally decided on Leaflet.js as a map provider and the use of React Leaflet components to facilitate the work and integration with the React components.
