### ISSUE TITLE
Adding the map in the mobile app, see what api is the best and ask the user for the location

### ISSUE THREAD

**Issue by uo269570** [Arquisoft/radarin_en3a#44]

**Comment by uo269570** [comment]
I am usint the expo-location library but while trying to obtain the location in the emulator this doesn't work properly while in my physical device it does.
I don't know how to solve this in the emulator because it has permisions to use the localization of it. How could we do this in the virtual device? @pglez82

**Comment by pglez82** [comment]
If I remember well, in the emulator you have to enable the location and give it a virtual longitude and latitude as obviously the emulator does not have gps.

Check out this link: https://stackoverflow.com/questions/2279647/how-to-emulate-gps-location-in-the-android-emulator
Pablo

**Comment by uo269570** [comment]
This is done, closing this issue
