### ISSUE TITLE
Join restapi with webapp

### ISSUE THREAD

**Issue by UO225811** [Arquisoft/radarin_en3a#55]

**Comment by uo269570** [comment]
While trying to put together the restapi and the webapp we found an error that we cannot solve really well. The function to add users does not seem to work properly we have an error 400 and a connection refused, we tried to solve this several times but this does not work. Here is the image with the error:
![WhatsApp Image 2021-04-12 at 00 27 41](https://user-images.githubusercontent.com/60401888/114324117-b6a20280-9b28-11eb-864f-0195901b0ac5.jpeg)

How can we solve this? @pglez82

**Comment by UO225811** [comment]
I tried executing docker and the database worked well without errors. 

![image](https://user-images.githubusercontent.com/60402138/114324988-d7208b80-9b2d-11eb-8579-d49907053150.png)

**Comment by UO269509** [comment]
I think, we must change the lines that we use "res.json()" to "res.send()" and probably, all the restapi is going to work.

**Comment by pglez82** [comment]
You need to make sure that the /users/add function in the restapi is working property. You can test that using [postman](https://www.postman.com/product/api-client/). Once you are sure that the restapi call works property, you can move forward and work in the api.
