### ISSUE TITLE
Join restapi with mobile app

### ISSUE THREAD

**Issue by UO225811** [Arquisoft/radarin_en3a#56]

**Comment by uo269570** [comment]
This does not seen to difficult, I researched some information about this and in this webpage we can see how we can do it. https://rapidapi.com/blog/how-to-make-rest-api-calls-in-react-native/ We onaly need an url and a fecth I think. And also a method in the API that responds or does something with the information that is received.

**Comment by uo269570** [comment]
The mobile app is in hold, so this will be done in the future if we continue to develop with the react-native
