### ISSUE TITLE
Change Documentation

### ISSUE THREAD

**Issue by uo269570** [Arquisoft/radarin_en3a#63]
Revising all the documentation I think this are the part we  need to update:
* 4.Solution stragety: we need to add info about the libraries we are using
* 5. Building block view: we need to update this
* 6 Runtime view: when everything is working we need to add images
* 7 Deployment view: same as before, when everything is working we need to update this.
* 8 Concepts: needs and update
* 9 Design decisions: we need to put the decisions we made and the problems with the mobile app
* 10 Quality: not really sure if we need to update this or not
* 11 Technical riks: maybe is a good practice to add some of the general problems we had here, but I don´t really know

@raulng9 @sergioRiestra @UO269509 @ArCampa @UO225811 @uo269570

**Comment by UO269509** [comment]
I already update the points 5 and 11.
