### ISSUE TITLE
Make the Actions work

### ISSUE THREAD

**Issue by uo269570** [Arquisoft/radarin_en3a#64]
I forked the project in order to change the .json files and other error to have the actions working. I did npm install, npm update ... and nothing seems to work. Maybe is because I am not really understanding the error we have here. How can we solve this problem? @pglez82

**Comment by uo269570** [comment]
I am looking at the actions we have and it seems that the problem with the .json files started after #105 because here the only problems we had were the test that did not run properly

**Comment by pglez82** [comment]
Try to clone the project locally, remove the package-lock.json, do `npm install` (this will generate a new package-lock.json) and push this new package-lock.json to the repository.

Let me know if that helps. If not I can take a closer look at the error.

**Comment by uo269570** [comment]
Doing what you told me changes the error, now we have some problems with the commits of the webapp and the test of the restapi but I think this will be easier to fix

**Comment by pglez82** [comment]
I have been checking the ouput of actions for the webapp and I think the problem are the warnings that you get (mostly unused imports) when executing `npm run build`. Check that the output is telling you: `Treating warnings as errors because process.env.CI = true.`. So you need to remove this warnings from the code and at least this error should disappear.

**Comment by uo269570** [comment]
Right now we have a problem with the restapi in the actions that we don't know how to solve. This says something about some IP, it seems a little strage. How can we solve this?

**Comment by UO225811** [comment]
We solved the restapi IP problem and now we can move on to check all the functionalities.

**Comment by UO269509** [comment]
I do some changes in the application and now we have pass both parts of the actions until the tests so we are going to the good direction
