### ISSUE TITLE
No node_modules should be uploaded to the repository

### ISSUE THREAD

**Issue by pglez82** [Arquisoft/radarin_en3a#69]
You have a node modules directory in the root of the repository. This is unnecessary and makes the repository very heavy. You should remove it.

**Comment by uo269570** [comment]
This sould be in the .gitignore right? Because we have it there but it also is uploaded, so we delete this before doing the push?

**Comment by pglez82** [comment]
It just do not make sense there in the project. You have a node_modules for the webapp and other for the restapi (both make sense as they are the libraries for the webapp and restapi). This two are not in the repository because I added them in the .gitignore in the initial repository. Then you have another node_modules for the mobile app, which is ok but it shouldn't be in github (should be ignored as well). The node_modules in the root of the repository I don't know to what code corresponds. For me it doesn't make sense there. If it does, at least should be ignored and not in the repository.

Here you have information about how to do it: https://stackoverflow.com/questions/7927230/remove-directory-from-remote-repository-after-adding-them-to-gitignore
