### ISSUE TITLE
Working with deployed app

### ISSUE THREAD

**Issue by uo269570** [Arquisoft/radarin_en3a#77]
While doing the deployment of the app some problems arised with the Cors. We got stuck and we don't really know how to solve this error. Whithout this we cannot see the changes in mongo or work with the database at all. How can we solve them? @pglez82

**Comment by pglez82** [comment]
You need to be a little more specific with the error for me to take a look at it. What is exactly failing? Where I can see the error? Does it happen in local in heroku or both?

When we created the radarin_0 project I added some cors configuration in the restapi so it accepts petitions from everywhere:
``` 
app.options('*', cors());
app.use(cors());
```

**Comment by uo269570** [comment]
This happens in heroku, when we do a log in in the app an then we do F12 the error appears. In the restapi we have the cors configured so I don't know where the problem is.

**Comment by uo269570** [comment]
![imagen](https://user-images.githubusercontent.com/60401888/114693026-781f6a00-9d19-11eb-8c25-0071eddfb8c7.png)
Here appear some errors we have. In the server.js we have the lines of the cors and also the Allow from origin. But I don´t know if we need more. I think this problem may arise also with the database because a teammate change the password of the admin user so the url to connect to mongo probably is not the correct one.

**Comment by uo269570** [comment]
Maybe is because of this, because the error code is 503

**Comment by pglez82** [comment]
Yes, The problem has anything to do with cors. If you log in to heroku, you can see the logs for the app radarinen3arestapi (see image attached). 
![image](https://user-images.githubusercontent.com/10683040/114696693-3ee8f900-9d1d-11eb-91f6-c388ce5ef291.png)
That means that the restapi is unable to authenticate with mongodb atlas. If you changed the password there is the error. In the github repository you have a github secret (under settings) called MONGO_URI. This secret has the connection string (including the password) for the mongo atlas db. You need to get the new connection string (you can log in mongo atlas for getting this connection string) and update the github secret with the new url. 

Another way of checking this without having to deploy to heroku would be to change the connection string locally from localhost (line 12 in file restapi/server.js) and put the mongo atlas connection string. When that works against mongo atlas, just take that url and place in the mongo_uri secret.

If you need further help let me know. Is not that easy to explain this in an issue.

**Comment by uo269570** [comment]
Ok, I think I know how to do this know, I will check this and I will tell you if this works. The secrect file I think I cannot access, I don´t have the settings tab of this repository.
![imagen](https://user-images.githubusercontent.com/60401888/114707588-b2ddce00-9d2a-11eb-8ea9-7dc7b2f5b606.png)

**Comment by pglez82** [comment]
I change the permissions to access the settings tab and the github secrets. You need that for make it work.

**Comment by pglez82** [comment]
@UO269509 @uo269570  It is a good practice when closing the issue to inform with a comment if the problem has been solved or not and how, so the full process is well documented. Specially, if someone is helping you out with it.

**Comment by UO269509** [comment]
Ok @pglez82, it was my fault, sorrry. Finanlly the issue was solved changing the password in Secrets because in one commit, doing some testing we changed the mongoUser password unintentionally.
