### ISSUE TITLE
Show the locations of friends on the map

### ISSUE THREAD

**Issue by raulng9** [Arquisoft/radarin_en3a#82]
Right now in the map we are showing the locations stored in the logged user's POD. We can try to include markers with the locations present on the database from the friends of the user.

**Comment by UO269509** [comment]
The steps I think we need is: 
-list your friends
-recieve a list of registered friends
-Do the same loop with your locations but with the friends and their locations and create a different color Marker
- Put in the tag the name of the friend

**Comment by raulng9** [comment]
Included the locations of friends in the map with a different marker color and a popup displaying the webId of the person.
