### ISSUE TITLE
Notifications in the webapp

### ISSUE THREAD

**Issue by uo269570** [Arquisoft/radarin_en3a#83]
We have a problem passing the friend list to de restapi function. The funtion works properly in the postman.

**Comment by UO269509** [comment]
I create a new branch to solve this problem (WebNotification), first of all I tried to send a hardcoded notification using the react-toastify library and it seems to work. The next step is to solve the parameters we are passing to the restapi.

**Comment by UO269509** [comment]
Now, he have notifications, the problem was that we return a json instead of text.

**Comment by uo269570** [comment]
I fixed some minor errors we had with the restapi and the webapp. Now the notifications are properly working

**Comment by uo269570** [comment]
Right now the basic funcionality of the notifications is implemented. Now I am trying to do something similar to the github bell button that shows when we have a notification in our app.

**Comment by uo269570** [comment]
Now we have in the nav a bell that tells us if we have some notification and each 30 seconds we can see the if we have a near friend. Now the only problem is to have it visually good and to solve a compiling error

**Comment by uo269570** [comment]
@pglez82 I have a compiling error that I don´t know how to solve. The screen is the next one. How can I fix this?
![imagen](https://user-images.githubusercontent.com/60401888/115608942-32e5d400-a2e7-11eb-8e89-2b42add18c79.png)

**Comment by pglez82** [comment]
Hi. It is not an error but a warning. The same problem is described here: https://stackoverflow.com/questions/55840294/how-to-fix-missing-dependency-warning-when-using-useeffect-react-hook

If nothing works, you can always disable the warning as described in the stackoverflow post.

**Comment by uo269570** [comment]
Fixed the error with the warning suppressing it, and also did that only one notification appeared in the window (before two notifications appeared). Now we only need to put the visual correct. But the notifications are done.
