### ISSUE TITLE
Usability of the webapp

### ISSUE THREAD

**Issue by uo269570** [Arquisoft/radarin_en3a#88]

**Comment by raulng9** [comment]
- Improve login UI
- Solve profile/main linking
- Clean logged-in message across webapp

**Comment by UO269509** [comment]
Now, I have removed the logged-in message and I improve the login and we only need to pute the username.

**Comment by uo269570** [comment]
I am going to take a look on how we can do a loading page for the app when we change into some other visual. So the user can see that the app is doing something and not the loading od the two pages.

**Comment by raulng9** [comment]
We fixed the profile linking and changed the location view/retrieval for improved usability, checking every 10 seconds and saving to the POD if the user chooses to with optional tag.

**Comment by raulng9** [comment]
Included comments for all of the webpage's components.

**Comment by raulng9** [comment]
We've increased the usability of the webapp in general terms, as well as the readability of the code.
